### ISSUE TITLE
Related Manga Section

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#6]
Linking mangas that related each other will be very nice and way easier to manage mangas.

**Comment by nilfoer** [comment]
You can use collections for that. All the collections a manga belongs to will be displayed on the book page with all the thumbnail covers.

Or do you need more than that functionality?

**Comment by ghost** [comment]
Ah totally I forgot them, For example I could have done to create a collection that called naruto and put naruto and its sequels. My bad. To be honest it would be more nice there were related manga section while looking book's detail but it is cool too. Thanks for your reply.

**Comment by ghost** [comment]
Collection's are nice but it is not that functional because if a manga has too many prequel and sequel it would really big trouble to keep track it, collection tag does sort mangas with their names so it would be mess and user probably lose its read order, sorry. There is no hurry, you could add this as add feature request.

**Comment by nilfoer** [comment]
Could you describe what functionality you're missing exactly? I could make it so you can assign a collection index or whatever that collections use for ordering, if that helps.

**Comment by ghost** [comment]
I am missing related series true order while adding them to collection, like there are 5 series that starts with the first one starts with p and the last one start with a, collection does add the last one as first. Giving number to collection series would work I think like 1,2,3. I am really sleep derived because of my exams I could not make any proper sentence if you did not understand I will write there again when I wake up, sorry.

**Comment by ghost** [comment]
I  think you could add, put in order mangas that on a particular collection by dragging.

**Comment by ghost** [comment]
Well, I guess most quick solution is writing reading order to collection's name.

**Comment by nilfoer** [comment]
The new version now has a page to edit the internal order of a collection and to rename the collection itself.

**Comment by ghost** [comment]
Works like a charm! thanks for your hardworking.

**Comment by ghost** [comment]
I get error while trying to change collections name after ordering mangas, guess it is minor bug 
```
07:03:38 - WARNING - Could not rename collection 'Goblin Slayer Side Story: Year
 One' to 'Goblin Slayer' since the new name already exists
```

**Comment by nilfoer** [comment]
The collection names are unique. So you have to either add the books to the already existing 'Goblin Slayer' or rename that to sth. else by going to `/edit-collection/Goblin Slayer` (or `/edit-collection/Goblin%20Slayer`) and then rename the other one. (I really should've added a way to delete a collection)

**Comment by ghost** [comment]
tried with `http://localhost:7578/book/edit-collection/Goblin%20Slayer` `http://localhost:7578/book/edit-collection/Goblin Slayer`
I just got 
```
 07:19:24 - ERROR - Exception on /book/edit-collection/Goblin Slayer [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2292, in wsgi_app
  File "flask\app.py", line 1815, in full_dispatch_request
  File "flask\app.py", line 1718, in handle_user_exception
  File "flask\_compat.py", line 35, in reraise
  File "flask\app.py", line 1813, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "manga_db\webGUI\webGUI.py", line 779, in show_edit_collection
  File "flask\templating.py", line 134, in render_template
  File "flask\templating.py", line 117, in _render
  File "jinja2\environment.py", line 1090, in render
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\edit_collection.html",
line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\layout.html", line 210,
 in top-level template code
    {% block body %}{% endblock %}
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\edit_collection.html",
line 50, in block "body"
    <div class="books-collection-grid" id="collection{{ collection_name.capitali
ze() }}">
  File "jinja2\environment.py", line 471, in getattr
jinja2.exceptions.UndefinedError: 'collection_name' is undefined
07:19:48 - INFO - 127.0.0.1 - - [08/Feb/2021 07:19:48] "←[35m←[1mGET /book/edit-
collection/Goblin%20Slayer HTTP/1.1←[0m" 500 -
07:19:48 - ERROR - Exception on /book/edit-collection/Goblin Slayer [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2292, in wsgi_app
  File "flask\app.py", line 1815, in full_dispatch_request
  File "flask\app.py", line 1718, in handle_user_exception
  File "flask\_compat.py", line 35, in reraise
  File "flask\app.py", line 1813, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "manga_db\webGUI\webGUI.py", line 779, in show_edit_collection
  File "flask\templating.py", line 134, in render_template
  File "flask\templating.py", line 117, in _render
  File "jinja2\environment.py", line 1090, in render
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\edit_collection.html",
line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\layout.html", line 210,
 in top-level template code
    {% block body %}{% endblock %}
  File "C:\Users\fuchi\mangadb\manga_db\webGUI\templates\edit_collection.html",
line 50, in block "body"
    <div class="books-collection-grid" id="collection{{ collection_name.capitali
ze() }}">
  File "jinja2\environment.py", line 471, in getattr
jinja2.exceptions.UndefinedError: 'collection_name' is undefined
07:19:48 - INFO - 127.0.0.1 - - [08/Feb/2021 07:19:48] "←[35m←[1mGET /book/edit-
collection/Goblin%20Slayer HTTP/1.1←[0m" 500 -
```

**Comment by nilfoer** [comment]
Okay that means there are no books in that collection. The alternative way should still work, while I work on the fix.

**Comment by ghost** [comment]
Okay good luck!

**Comment by nilfoer** [comment]
In [v0.24.0](https://github.com/nilfoer/mangadb/releases/tag/v.0.24.0) it should now show you an error message in the webGUI if the name isn't unique and it should include a link to the collection that's blocking the rename. I also added a button to delete the collection and a page where all collections are listed (so you can delete collections without any books in them).

**Comment by ghost** [comment]
It seems everythings works now, thanks for your working. If something would occur I wil let you know
